### ISSUE TITLE
Meaning of wb codes

### ISSUE THREAD

**Issue by MichaelW17** [mahmoudnafifi/WB_color_augmenter#1]
Could you explain what the letters "C/D/F/T/S" means in, like '_F_AS' and '_T_CS'? 
Much appreciate it.

**Comment by mahmoudnafifi** [comment]
Hi @MichaelW17,
Here the info you asked for:
C for cloudy WB (6500 K)
D for daylight WB (5500 K)
F for fluorescent WB (3800 K)
S for shade WB (7500K)
T for incandescent or tungsten WB (2850K)
Also the terms AS and CS refer to Adobe Standard and Camera Standard picture style, each one represents a different photofinishing profile.

**Comment by pratobad** [comment]
@mahmoudnafifi I had one question, like could this augmentation be camera specific (if it could be), because I assume different camera models have different internal formulas for white balance calculation, so adding to the question which camera images were used for this (if you have any idea regarding this)?

**Comment by mahmoudnafifi** [comment]
Thanks for the question. This is not camera-specific. The mapping was computed using different cameras, and you can think of it as augmenting images with color casts caused by a meta-camera’s white balance errors in the final display image. If you're referring to augmenting raw images with different illumination casts in the linear space, this work does not do that. Instead, it operates directly in the display sRGB space.
